log:
  file: 'streamlake.log'
  #FATAL
  #ERROR
  #WARNING
  #INFO
  #DEBUG
  #NOTSET
  level: 'INFO'
  rotation: '100 MB'

gen:
  file_path: ''
  size_mb: 10
  max_size_mb_per_file: 5
  http_protocol:
    file_path: ''
    size_mb: 20
  g_protocol:
    file_path: ''
    size_mb:
  dns_protocol:
    file_path: ''
    size_mb: 30

